import Foundation

public struct HIGRenderer: Sendable {

  // MARK: - Public rendering

  public static func renderHIGFromJSON(
    data: HIGPageJSON, path: String
  ) -> String {
    var markdown = ""

    let sourceUrl =
      "https://developer.apple.com/design/human-interface-guidelines/\(path)"

    // Front matter
    markdown += generateHIGFrontMatter(data: data, sourceUrl: sourceUrl)

    // Breadcrumbs
    let breadcrumbs = generateHIGBreadcrumbs(sourceUrl: sourceUrl)
    if !breadcrumbs.isEmpty {
      markdown += breadcrumbs
    }

    // Role heading
    let roleDisplay =
      data.metadata.role == "collectionGroup" ? "Guide Collection" : data.metadata.role
    markdown += "**\(roleDisplay)**\n\n"

    // Title
    if !data.metadata.title.isEmpty {
      markdown += "# \(data.metadata.title)\n\n"
    }

    // Abstract
    let abstractText =
      data.abstract
      .filter { $0.type == "text" }
      .compactMap { $0.text }
      .joined()
    if !abstractText.trimmingCharacters(in: .whitespaces).isEmpty {
      markdown += "> \(abstractText)\n\n"
    }

    // Primary content sections
    for section in data.primaryContentSections {
      if section.kind == "content", let content = section.content {
        markdown += renderHIGContent(sections: content, references: data.references)
      }
    }

    // Regular sections
    if !data.sections.isEmpty {
      markdown += renderHIGContent(sections: data.sections, references: data.references)
    }

    // Topic sections (unless hidden)
    if let topicSections = data.topicSections, data.topicSectionsStyle != "hidden" {
      markdown += Self.renderHIGTopicSections(topicSections, references: data.references)
    }

    markdown = markdown.trimmingCharacters(in: .whitespacesAndNewlines)

    // Footer
    markdown += "\n\n---\n\n"
    markdown +=
      "*Generated by [swift-developer-docs-mcp](https://github.com/mehmetbaykar/swift-developer-docs-mcp) - Making Apple docs AI-readable.*\n"
    markdown +=
      "*This is unofficial content. All Human Interface Guidelines belong to Apple Inc.*\n"

    return markdown
  }

  public static func renderHIGTableOfContents(toc: HIGTableOfContents) -> String {
    var markdown = ""

    // Front matter
    markdown += "---\n"
    markdown += "title: Human Interface Guidelines\n"
    markdown +=
      "description: Apple's Human Interface Guidelines - Complete table of contents\n"
    markdown +=
      "source: https://developer.apple.com/design/human-interface-guidelines/\n"
    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    markdown += "timestamp: \(formatter.string(from: Date()))\n"
    markdown += "---\n\n"

    // Title
    markdown += "# Human Interface Guidelines\n\n"
    markdown +=
      "> Apple's comprehensive guide to designing interfaces for all Apple platforms.\n\n"

    // ToC items
    markdown += Self.renderHIGTocItems(toc.interfaceLanguages.swift, headingLevel: 2)

    // Footer
    markdown += "\n\n---\n\n"
    markdown +=
      "*Generated by [swift-developer-docs-mcp](https://github.com/mehmetbaykar/swift-developer-docs-mcp) - Making Apple docs AI-readable.*\n"
    markdown +=
      "*This is unofficial content. All Human Interface Guidelines belong to Apple Inc.*\n"

    return markdown
  }

  // MARK: - Front matter & breadcrumbs

  private static func generateHIGFrontMatter(data: HIGPageJSON, sourceUrl: String) -> String {
    var lines: [String] = []

    if !data.metadata.title.isEmpty {
      lines.append("title: \(data.metadata.title)")
    }

    let description =
      data.abstract
      .filter { $0.type == "text" }
      .compactMap { $0.text }
      .joined()
      .trimmingCharacters(in: .whitespaces)
    if !description.isEmpty {
      lines.append("description: \(description)")
    }

    lines.append("source: \(sourceUrl)")

    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    lines.append("timestamp: \(formatter.string(from: Date()))")

    return "---\n\(lines.joined(separator: "\n"))\n---\n\n"
  }

  private static func generateHIGBreadcrumbs(sourceUrl: String) -> String {
    guard let url = URL(string: sourceUrl) else { return "" }
    let pathParts = url.pathComponents.filter { $0 != "/" }

    // Need at least /design/human-interface-guidelines + something
    guard pathParts.count >= 3 else { return "" }

    var breadcrumbs =
      "**Navigation:** [Human Interface Guidelines](/design/human-interface-guidelines)"

    // Add breadcrumbs for parts after /design/human-interface-guidelines/
    for i in 2..<pathParts.count {
      let part = pathParts[i]
      let path = "/" + pathParts[0...i].joined(separator: "/")
      let formattedPart = Self.formatBreadcrumbPart(part)
      breadcrumbs += " \u{203A} [\(formattedPart)](\(path))"
    }

    return "\(breadcrumbs)\n\n"
  }

  private static func formatBreadcrumbPart(_ part: String) -> String {
    part.replacingOccurrences(of: "-", with: " ")
      .split(separator: " ")
      .map { word in
        word.prefix(1).uppercased() + word.dropFirst()
      }
      .joined(separator: " ")
  }

  // MARK: - Content rendering

  static func renderHIGContent(
    sections: [ContentItem],
    references: [String: HIGReferenceItem]
  ) -> String {
    var markdown = ""

    for item in sections {
      if item.type == "links",
        let items = item.items,
        item.style == "compactGrid"
      {
        for linkItem in items {
          if let linkId = linkItem.identifier ?? linkItem.text {
            if let refItem = references[linkId] {
              switch refItem {
              case .topic(let ref):
                markdown += "- [\(ref.title)](\(ref.url))"
                if let abstract = ref.abstract {
                  let text = abstract.compactMap { $0.text }.joined()
                  if !text.isEmpty {
                    markdown += " - \(text)"
                  }
                }
                markdown += "\n"
              case .external(let ref):
                markdown += "- [\(ref.title)](\(ref.url))\n"
              case .image:
                break
              }
            }
          }
        }
        markdown += "\n"
      } else {
        markdown += Self.renderContentItem(item, references: references)
      }
    }

    return markdown
  }

  private static func renderContentItem(
    _ item: ContentItem,
    references: [String: HIGReferenceItem]
  ) -> String {
    var markdown = ""

    switch item.type {
    case "heading":
      let level = min(item.level ?? 2, 6)
      let hashes = String(repeating: "#", count: level)
      markdown += "\(hashes) \(item.text ?? "")\n\n"

    case "paragraph":
      if let inlineContent = item.inlineContent {
        let text = Self.renderHIGInlineContent(inlineContent, references: references)
        markdown += "\(text)\n\n"
      }

    case "codeListing":
      var code = ""
      if let codeValue = item.code {
        switch codeValue {
        case .single(let s): code = s
        case .multiple(let arr): code = arr.joined(separator: "\n")
        }
      }
      let syntax = item.syntax ?? "swift"
      markdown += "```\(syntax)\n\(code)\n```\n\n"

    case "unorderedList":
      if let items = item.items {
        for listItem in items {
          let itemText = Self.renderHIGContent(
            sections: listItem.content ?? [], references: references)
          markdown +=
            "- \(itemText.replacingOccurrences(of: "\\n\\n$", with: "", options: .regularExpression))\n"
        }
        markdown += "\n"
      }

    case "orderedList":
      if let items = item.items {
        for (index, listItem) in items.enumerated() {
          let itemText = Self.renderHIGContent(
            sections: listItem.content ?? [], references: references)
          markdown +=
            "\(index + 1). \(itemText.replacingOccurrences(of: "\\n\\n$", with: "", options: .regularExpression))\n"
        }
        markdown += "\n"
      }

    case "table":
      markdown += Self.renderHIGTable(item, references: references)

    case "aside":
      markdown += Self.renderHIGAside(item, references: references)

    case "row":
      markdown += Self.renderHIGRow(item, references: references)

    case "video":
      markdown += Self.renderHIGVideo(item, references: references)

    default:
      break
    }

    return markdown
  }

  // MARK: - Table rendering

  static func renderHIGTable(
    _ item: ContentItem,
    references: [String: HIGReferenceItem]
  ) -> String {
    guard let rows = item.rows, !rows.isEmpty else { return "" }

    let firstRowIsHeader = item.header == "row"
    var markdown = ""

    for (rowIndex, row) in rows.enumerated() {
      let cellTexts = row.map { cell -> String in
        let text = Self.renderHIGContent(sections: cell, references: references)
        return Self.escapeTableCell(text)
      }
      guard !cellTexts.isEmpty else { continue }
      markdown += "| \(cellTexts.joined(separator: " | ")) |\n"
      if firstRowIsHeader && rowIndex == 0 {
        markdown += "| \(cellTexts.map { _ in "---" }.joined(separator: " | ")) |\n"
      }
    }

    return markdown.isEmpty ? "" : "\(markdown)\n"
  }

  private static func escapeTableCell(_ text: String) -> String {
    text.replacingOccurrences(of: "|", with: "\\|")
      .replacingOccurrences(of: "\n", with: " ")
      .trimmingCharacters(in: .whitespacesAndNewlines)
  }

  // MARK: - Aside rendering

  static func renderHIGAside(
    _ item: ContentItem,
    references: [String: HIGReferenceItem]
  ) -> String {
    let rawType = (item.style ?? item.name ?? "note").lowercased()
    let calloutType = Self.mapHIGAsideStyleToCallout(rawType)
    let asideContent =
      item.content != nil
      ? Self.renderHIGContent(sections: item.content!, references: references)
      : ""
    let cleanContent = asideContent.trimmingCharacters(in: .whitespacesAndNewlines)
      .replacingOccurrences(of: "\n", with: "\n> ")
    if cleanContent.isEmpty { return "" }
    return "> [!\(calloutType)]\n> \(cleanContent)\n\n"
  }

  // MARK: - Row rendering

  static func renderHIGRow(
    _ item: ContentItem,
    references: [String: HIGReferenceItem]
  ) -> String {
    // HIG rows use "columns" in JSON, which maps to item.content in ContentItem.
    // Each column has its own content array.
    guard let columns = item.content, !columns.isEmpty else { return "" }

    var markdown = ""
    for column in columns {
      if let colContent = column.content, !colContent.isEmpty {
        markdown += Self.renderHIGContent(sections: colContent, references: references)
      }
    }
    return markdown
  }

  // MARK: - Video rendering

  static func renderHIGVideo(
    _ item: ContentItem,
    references: [String: HIGReferenceItem]
  ) -> String {
    guard let identifier = item.identifier else { return "" }
    guard let refItem = references[identifier] else { return "" }

    switch refItem {
    case .image(let imageRef):
      guard let videoUrl = imageRef.variants.first?.url else { return "" }
      // Prefer abstract text from the item, then ref alt, then fallback
      let abstractText =
        item.abstract?
        .filter { $0.type == "text" }
        .compactMap { $0.text }
        .joined()
        .trimmingCharacters(in: .whitespaces)
      let label =
        (abstractText?.isEmpty == false ? abstractText : nil)
        ?? imageRef.alt ?? "Video"
      return "[\(label)](\(videoUrl))\n\n"
    default:
      return ""
    }
  }

  // MARK: - Inline content rendering

  static func renderHIGInlineContent(
    _ inlineContent: [ContentItem],
    references: [String: HIGReferenceItem]
  ) -> String {
    var result = ""
    for item in inlineContent {
      switch item.type {
      case "text":
        result += item.text ?? ""

      case "codeVoice":
        if let codeValue = item.code {
          switch codeValue {
          case .single(let s): result += "`\(s)`"
          case .multiple(let arr): result += "`\(arr.joined())`"
          }
        }

      case "reference":
        let refItem =
          item.identifier != nil ? references[item.identifier!] : nil
        let refTitle: String?
        let refUrl: String
        switch refItem {
        case .topic(let ref):
          refTitle = ref.title
          refUrl = ref.url
        case .external(let ref):
          refTitle = ref.title
          refUrl = ref.url
        case .image(let ref):
          refTitle = nil
          refUrl = ref.variants.first?.url ?? "#"
        case nil:
          refTitle = nil
          refUrl = "#"
        }
        let title =
          item.title ?? item.text ?? refTitle
          ?? (item.identifier.map(Self.extractTitleFromIdentifier) ?? "")
        let url: String
        if case .image = refItem {
          url = "#"
        } else {
          url = refUrl
        }
        result += "[\(title)](\(url))"

      case "emphasis":
        let inner =
          item.inlineContent != nil
          ? Self.renderHIGInlineContent(item.inlineContent!, references: references)
          : ""
        result += "*\(inner)*"

      case "strong":
        let inner =
          item.inlineContent != nil
          ? Self.renderHIGInlineContent(item.inlineContent!, references: references)
          : ""
        result += "**\(inner)**"

      case "image":
        if let identifier = item.identifier, let refItem = references[identifier] {
          if case .image(let imageRef) = refItem {
            if let imageUrl = imageRef.variants.first?.url {
              result += "![\(imageRef.alt ?? "")](\(imageUrl))"
            }
          }
        }

      default:
        result += item.text ?? ""
      }
    }
    return result
  }

  // MARK: - Topic sections

  static func renderHIGTopicSections(
    _ topicSections: [HIGTopicSection],
    references: [String: HIGReferenceItem]
  ) -> String {
    var markdown = ""

    for section in topicSections {
      if let title = section.title {
        markdown += "## \(title)\n\n"
      }

      for id in section.identifiers {
        guard let refItem = references[id] else { continue }
        switch refItem {
        case .topic(let ref):
          markdown += "- [\(ref.title)](\(ref.url))"
          if let abstract = ref.abstract {
            let text = abstract.compactMap { $0.text }.joined()
            if !text.isEmpty {
              markdown += " - \(text)"
            }
          }
          markdown += "\n"
        case .external(let ref):
          markdown += "- [\(ref.title)](\(ref.url))\n"
        case .image:
          break
        }
      }
      markdown += "\n"
    }

    return markdown
  }

  // MARK: - ToC items

  static func renderHIGTocItems(_ items: [HIGTocItem], headingLevel: Int) -> String {
    var markdown = ""

    for item in items {
      if item.type == "module" || item.type == "symbol" {
        let hashes = String(repeating: "#", count: min(headingLevel, 6))
        markdown += "\(hashes) \(item.title)\n\n"

        if let children = item.children {
          markdown += Self.renderHIGTocItems(children, headingLevel: headingLevel + 1)
        }
      } else if item.type == "article" {
        markdown += "- [\(item.title)](\(item.path))\n"
      }
    }

    return markdown
  }

  // MARK: - Helpers

  private static func mapHIGAsideStyleToCallout(_ style: String) -> String {
    switch style.lowercased() {
    case "warning": return "WARNING"
    case "important": return "IMPORTANT"
    case "caution": return "CAUTION"
    case "tip": return "TIP"
    case "deprecated": return "WARNING"
    default: return "NOTE"
    }
  }

  private static func extractTitleFromIdentifier(_ identifier: String) -> String {
    let parts = identifier.split(separator: "/")
    guard let lastPart = parts.last else { return identifier }
    return String(lastPart)
      .replacingOccurrences(of: "-", with: " ")
  }
}
