import Foundation

public struct DocumentRenderer: Sendable {
    private static let maxContentDepth = 50
    private static let maxInlineDepth = 20
    public static let minContentLength = 100

    public static func renderFromJSON(_ jsonData: AppleDocJSON, sourceURL: String) -> String {
        var markdown = ""

        markdown += generateFrontMatter(jsonData, sourceURL: sourceURL)

        let breadcrumbs = generateBreadcrumbs(sourceURL)
        if !breadcrumbs.isEmpty {
            markdown += breadcrumbs
        }

        if let roleHeading = jsonData.metadata?.roleHeading {
            markdown += "**\(roleHeading)**\n\n"
        }

        if let title = jsonData.metadata?.title, !title.isEmpty {
            markdown += "# \(title)\n\n"
        }

        if let platforms = jsonData.metadata?.platforms, !platforms.isEmpty {
            let platformText = platforms.map { p in
                "\(p.name) \(p.introducedAt)+\(p.beta == true ? " Beta" : "")"
            }.joined(separator: ", ")
            markdown += "**Available on:** \(platformText)\n\n"
        }

        if let abstract = jsonData.abstract {
            let abstractText = abstract
                .filter { $0.type == "text" }
                .compactMap { $0.text }
                .joined()
            if !abstractText.trimmingCharacters(in: .whitespaces).isEmpty {
                markdown += "> \(abstractText)\n\n"
            }
        }

        if let primarySections = jsonData.primaryContentSections {
            let declarationSection = primarySections.first { $0.kind == "declarations" }
            if let declarations = declarationSection?.declarations {
                markdown += renderDeclarations(declarations)
            }

            let parametersSection = primarySections.first { $0.kind == "parameters" }
            if let parameters = parametersSection?.parameters {
                markdown += renderParameters(parameters, references: jsonData.references)
            }

            let contentSections = primarySections.filter { $0.kind == "content" }
            for section in contentSections {
                if let content = section.content {
                    markdown += renderContentArray(content, references: jsonData.references)
                }
            }
        }

        if let relationships = jsonData.relationshipsSections {
            markdown += renderRelationships(relationships, variants: jsonData.variants, refs: jsonData.references)
        }

        if let topics = jsonData.topicSections {
            markdown += renderTopicSections(topics, variants: jsonData.variants, refs: jsonData.references)
        }

        if let swiftItems = jsonData.interfaceLanguages?.swift,
           let first = swiftItems.first,
           let children = first.children {
            let indexItems = children.map { swiftItemToIndexItem($0) }
            markdown += renderIndexContent(indexItems)
        }

        if let seeAlso = jsonData.seeAlsoSections {
            markdown += renderSeeAlso(seeAlso, variants: jsonData.variants, refs: jsonData.references)
        }

        markdown = markdown.trimmingCharacters(in: .whitespacesAndNewlines)

        markdown += "\n\n---\n\n"
        markdown += "*Generated by [swift-developer-docs-mcp](https://github.com/mehmetbaykar/swift-developer-docs-mcp) - Making Apple docs AI-readable.*\n"
        markdown += "*This is unofficial content. All documentation belongs to Apple Inc.*\n"

        return markdown
    }

    private static func swiftItemToIndexItem(_ item: SwiftInterfaceItem) -> IndexContentItem {
        IndexContentItem(
            type: item.type,
            title: item.title,
            path: item.path,
            beta: item.beta,
            children: item.children?.map { swiftItemToIndexItem($0) }
        )
    }

    static func generateFrontMatter(_ data: AppleDocJSON, sourceURL: String) -> String {
        var lines: [String] = []

        if let title = data.metadata?.title {
            let cleanTitle = title.replacingOccurrences(of: "| Apple Developer Documentation", with: "").trimmingCharacters(in: .whitespaces)
            lines.append("title: \(cleanTitle)")
        } else if let swiftTitle = data.interfaceLanguages?.swift?.first?.title {
            lines.append("title: \(swiftTitle)")
        }

        if let abstract = data.abstract {
            let description = abstract
                .filter { $0.type == "text" }
                .compactMap { $0.text }
                .joined()
                .trimmingCharacters(in: .whitespaces)
            if !description.isEmpty {
                lines.append("description: \(description)")
            }
        }

        lines.append("source: \(sourceURL)")

        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        lines.append("timestamp: \(formatter.string(from: Date()))")

        return "---\n\(lines.joined(separator: "\n"))\n---\n\n"
    }

    static func generateBreadcrumbs(_ sourceURL: String) -> String {
        guard let url = URL(string: sourceURL) else { return "" }
        let pathParts = url.pathComponents.filter { $0 != "/" }

        if pathParts.count < 3 { return "" }

        let framework = pathParts[1]
        let capitalizedFramework = framework.prefix(1).uppercased() + framework.dropFirst()
        var breadcrumbs = "**Navigation:** [\(capitalizedFramework)](/documentation/\(framework))"

        if pathParts.count > 3 {
            for i in 2..<(pathParts.count - 1) {
                let part = pathParts[i]
                let path = pathParts[0...i].joined(separator: "/")
                breadcrumbs += " › [\(part)](/\(path))"
            }
        }

        return "\(breadcrumbs)\n\n"
    }

    static func renderDeclarations(_ declarations: [Declaration]) -> String {
        var markdown = ""
        for decl in declarations {
            guard let tokens = decl.tokens else { continue }
            let code = tokens
                .compactMap { $0.text }
                .joined()
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !code.isEmpty {
                markdown += "```swift\n\(code)\n```\n\n"
            }
        }
        return markdown
    }

    static func renderParameters(_ params: [Parameter], references: [String: ContentItem]?) -> String {
        if params.isEmpty { return "" }
        var markdown = "## Parameters\n\n"
        for param in params {
            markdown += "**\(param.name)**\n\n"
            if let content = param.content {
                let paramText = renderContentArray(content, references: references, depth: 0)
                markdown += "\(paramText)\n\n"
            }
        }
        return markdown
    }

    static func renderContentArray(_ content: [ContentItem], references: [String: ContentItem]?, depth: Int = 0) -> String {
        if depth > maxContentDepth {
            return "[Content too deeply nested]"
        }

        var markdown = ""
        for item in content {
            switch item.type {
            case "heading":
                let level = min(item.level ?? 2, 6)
                let hashes = String(repeating: "#", count: level)
                markdown += "\(hashes) \(item.text ?? "")\n\n"

            case "paragraph":
                if let inlineContent = item.inlineContent {
                    let text = renderInlineContent(inlineContent, references: references, depth: depth)
                    markdown += "\(text)\n\n"
                }

            case "codeListing":
                var code = ""
                if let codeValue = item.code {
                    switch codeValue {
                    case .single(let s): code = s
                    case .multiple(let arr): code = arr.joined(separator: "\n")
                    }
                }
                let syntax = item.syntax ?? "swift"
                markdown += "```\(syntax)\n\(code)\n```\n\n"

            case "unorderedList":
                if let items = item.items {
                    for listItem in items {
                        let itemText = renderContentArray(listItem.content ?? [], references: references, depth: depth + 1)
                        markdown += "- \(itemText.replacingOccurrences(of: "\\n\\n$", with: "", options: .regularExpression))\n"
                    }
                    markdown += "\n"
                }

            case "orderedList":
                if let items = item.items {
                    for (index, listItem) in items.enumerated() {
                        let itemText = renderContentArray(listItem.content ?? [], references: references, depth: depth + 1)
                        markdown += "\(index + 1). \(itemText.replacingOccurrences(of: "\\n\\n$", with: "", options: .regularExpression))\n"
                    }
                    markdown += "\n"
                }

            case "aside":
                let style = item.style ?? "note"
                let calloutType = mapAsideStyleToCallout(style)
                let asideContent = item.content != nil
                    ? renderContentArray(item.content!, references: references, depth: depth + 1)
                    : ""
                let cleanContent = asideContent.trimmingCharacters(in: .whitespacesAndNewlines)
                    .replacingOccurrences(of: "\n", with: "\n> ")
                markdown += "> [!\(calloutType)]\n> \(cleanContent)\n\n"

            default:
                break
            }
        }
        return markdown
    }

    static func renderInlineContent(_ inlineContent: [ContentItem], references: [String: ContentItem]?, depth: Int = 0) -> String {
        if depth > maxInlineDepth {
            return "[Inline content too deeply nested]"
        }

        return inlineContent.map { item in
            switch item.type {
            case "text":
                return item.text ?? ""
            case "codeVoice":
                if let codeValue = item.code {
                    switch codeValue {
                    case .single(let s): return "`\(s)`"
                    case .multiple(let arr): return "`\(arr.joined())`"
                    }
                }
                return ""
            case "reference":
                let title = item.title ?? item.text ?? ""
                let url = item.identifier != nil
                    ? convertIdentifierToURL(item.identifier!, references: references)
                    : ""
                return "[\(title)](\(url))"
            case "emphasis":
                let inner = item.inlineContent != nil
                    ? renderInlineContent(item.inlineContent!, references: references, depth: depth + 1)
                    : ""
                return "*\(inner)*"
            case "strong":
                let inner = item.inlineContent != nil
                    ? renderInlineContent(item.inlineContent!, references: references, depth: depth + 1)
                    : ""
                return "**\(inner)**"
            default:
                return item.text ?? ""
            }
        }.joined()
    }

    static func renderRelationships(_ rels: [ContentItem], variants: [ContentItem]?, refs: [String: ContentItem]?) -> String {
        var markdown = ""
        for rel in rels {
            guard let title = rel.title, let identifiers = rel.identifiers else { continue }
            markdown += "## \(title)\n\n"
            for id in identifiers {
                let info = variants?.first { $0.identifier == id }
                let reference = refs?[id]
                let displayTitle = info?.title ?? reference?.title ?? extractTitleFromIdentifier(id)
                let url = convertIdentifierToURL(id, references: refs)
                markdown += "- [\(displayTitle)](\(url))\n"
            }
            markdown += "\n"
        }
        return markdown
    }

    static func renderTopicSections(_ topics: [TopicSection], variants: [ContentItem]?, refs: [String: ContentItem]?) -> String {
        var markdown = ""
        for topic in topics {
            markdown += "## \(topic.title)\n\n"
            if let identifiers = topic.identifiers {
                for id in identifiers {
                    let info = variants?.first { $0.identifier == id }
                    let reference = refs?[id]
                    if info != nil || reference != nil {
                        let displayTitle = info?.title ?? reference?.title ?? extractTitleFromIdentifier(id)
                        let url = convertIdentifierToURL(id, references: refs)
                        var abstractText = ""
                        if let infoAbstract = info?.abstract {
                            abstractText = infoAbstract.compactMap { $0.text }.joined()
                        } else if let refAbstract = reference?.abstract {
                            abstractText = refAbstract.compactMap { $0.text }.joined()
                        }
                        markdown += "- [\(displayTitle)](\(url))"
                        if !abstractText.isEmpty {
                            markdown += " \(abstractText)"
                        }
                        markdown += "\n"
                    } else {
                        let displayTitle = extractTitleFromIdentifier(id)
                        let url = convertIdentifierToURL(id, references: refs)
                        markdown += "- [\(displayTitle)](\(url))\n"
                    }
                }
                markdown += "\n"
            }
        }
        return markdown
    }

    static func renderIndexContent(_ children: [IndexContentItem]) -> String {
        renderIndexContentWithIndent(children, headingLevel: 2)
    }

    static func renderIndexContentWithIndent(_ children: [IndexContentItem], headingLevel: Int) -> String {
        var markdown = ""
        for (i, child) in children.enumerated() {
            if child.type == "groupMarker" {
                if i > 0 { markdown += "\n" }
                let hashes = String(repeating: "#", count: min(headingLevel, 6))
                markdown += "\(hashes) \(child.title ?? "")\n\n"
            } else if let path = child.path, let title = child.title {
                let beta = child.beta == true ? " **Beta**" : ""
                markdown += "- [\(title)](\(path))\(beta)\n"
                if let nestedChildren = child.children {
                    markdown += "\n"
                    markdown += renderIndexContentWithIndent(nestedChildren, headingLevel: headingLevel + 1)
                }
            }
        }
        return markdown
    }

    static func renderSeeAlso(_ sections: [SeeAlsoSection], variants: [ContentItem]?, refs: [String: ContentItem]?) -> String {
        var markdown = ""
        for section in sections {
            guard let identifiers = section.identifiers else { continue }
            markdown += "## \(section.title)\n\n"
            for id in identifiers {
                let info = variants?.first { $0.identifier == id }
                let reference = refs?[id]
                let displayTitle = info?.title ?? reference?.title ?? extractTitleFromIdentifier(id)
                let url = convertIdentifierToURL(id, references: refs)
                markdown += "- [\(displayTitle)](\(url))\n"
            }
            markdown += "\n"
        }
        return markdown
    }

    static func mapAsideStyleToCallout(_ style: String) -> String {
        switch style.lowercased() {
        case "warning": return "WARNING"
        case "important": return "IMPORTANT"
        case "caution": return "CAUTION"
        case "tip": return "TIP"
        case "deprecated": return "WARNING"
        default: return "NOTE"
        }
    }

    static func convertIdentifierToURL(_ identifier: String, references: [String: ContentItem]?) -> String {
        if let reference = references?[identifier], let url = reference.url {
            return url
        }

        if identifier.hasPrefix("doc://com.apple.SwiftUI/documentation/") {
            return identifier.replacingOccurrences(
                of: "doc://com.apple.SwiftUI/documentation/",
                with: "/documentation/"
            )
        } else if identifier.hasPrefix("doc://com.apple.") {
            if let range = identifier.range(of: #"\/documentation\/(.+)"#, options: .regularExpression) {
                return String(identifier[range])
            }
        }
        return identifier
    }

    static func extractTitleFromIdentifier(_ identifier: String) -> String {
        let parts = identifier.split(separator: "/")
        guard let lastPart = parts.last else { return identifier }
        let lastStr = String(lastPart)

        if let match = lastStr.range(of: #"^(.+?)(?:-\w+)?$"#, options: .regularExpression) {
            let methodSignature = String(lastStr[match])

            // Try to extract just the part before the disambiguation suffix
            if let dashRange = lastStr.range(of: #"-[a-z0-9]+$"#, options: .regularExpression) {
                let withoutSuffix = String(lastStr[lastStr.startIndex..<dashRange.lowerBound])
                if withoutSuffix.contains("(") && withoutSuffix.contains(")") {
                    return withoutSuffix
                }
            }

            if methodSignature.contains("(") && methodSignature.contains(")") {
                return methodSignature
            }
        }

        return lastStr
            .replacingOccurrences(of: #"([a-z])([A-Z])"#, with: "$1 $2", options: .regularExpression)
            .replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespaces)
    }
}
