import Foundation

public typealias DocumentRenderer = ReferenceRenderer

public struct ReferenceRenderer: Sendable {
  public static let minContentLength = 100

  public static func renderFromJSON(_ jsonData: AppleDocJSON, sourceURL: String) -> String {
    var markdown = ""

    markdown += generateFrontMatter(jsonData, sourceURL: sourceURL)

    let breadcrumbs = generateBreadcrumbs(sourceURL)
    if !breadcrumbs.isEmpty {
      markdown += breadcrumbs
    }

    if let roleHeading = jsonData.metadata?.roleHeading {
      markdown += "**\(roleHeading)**\n\n"
    }

    if let title = jsonData.metadata?.title, !title.isEmpty {
      markdown += "# \(title)\n\n"
    }

    if let platforms = jsonData.metadata?.platforms, !platforms.isEmpty {
      let platformText = platforms.map { p in
        "\(p.name) \(p.introducedAt)+\(p.beta == true ? " Beta" : "")"
      }.joined(separator: ", ")
      markdown += "**Available on:** \(platformText)\n\n"
    }

    if let abstract = jsonData.abstract {
      let abstractText =
        abstract
        .filter { $0.type == "text" }
        .compactMap { $0.text }
        .joined()
      if !abstractText.trimmingCharacters(in: .whitespaces).isEmpty {
        markdown += "> \(abstractText)\n\n"
      }
    }

    if let primarySections = jsonData.primaryContentSections {
      let declarationSection = primarySections.first { $0.kind == "declarations" }
      if let declarations = declarationSection?.declarations {
        markdown += renderDeclarations(declarations)
      }

      let parametersSection = primarySections.first { $0.kind == "parameters" }
      if let parameters = parametersSection?.parameters {
        markdown += renderParameters(parameters, references: jsonData.references)
      }

      let propertiesSection = primarySections.first { $0.kind == "properties" }
      if let properties = propertiesSection?.items {
        markdown += ContentRenderer.renderProperties(properties, references: jsonData.references)
      }

      let contentSections = primarySections.filter { $0.kind == "content" }
      for section in contentSections {
        if let content = section.content {
          markdown += renderContentArray(content, references: jsonData.references)
        }
      }
    }

    if let relationships = jsonData.relationshipsSections {
      markdown += renderRelationships(
        relationships, variants: jsonData.variants, refs: jsonData.references)
    }

    if let topics = jsonData.topicSections {
      markdown += renderTopicSections(
        topics, variants: jsonData.variants, refs: jsonData.references)
    }

    if let swiftItems = jsonData.interfaceLanguages?.swift,
      let first = swiftItems.first,
      let children = first.children
    {
      let indexItems = children.map { swiftItemToIndexItem($0) }
      markdown += renderIndexContent(indexItems)
    }

    if let seeAlso = jsonData.seeAlsoSections {
      markdown += renderSeeAlso(seeAlso, variants: jsonData.variants, refs: jsonData.references)
    }

    markdown = markdown.trimmingCharacters(in: .whitespacesAndNewlines)

    markdown += "\n\n---\n\n"
    markdown +=
      "*Generated by [swift-developer-docs-mcp](https://github.com/mehmetbaykar/swift-developer-docs-mcp) - Making Apple docs AI-readable.*\n"
    markdown += "*This is unofficial content. All documentation belongs to Apple Inc.*\n"

    return markdown
  }

  // MARK: - Private Helpers

  private static func swiftItemToIndexItem(_ item: SwiftInterfaceItem) -> IndexContentItem {
    IndexContentItem(
      type: item.type,
      title: item.title,
      path: item.path,
      beta: item.beta,
      children: item.children?.map { swiftItemToIndexItem($0) }
    )
  }

  static func generateFrontMatter(_ data: AppleDocJSON, sourceURL: String) -> String {
    var lines: [String] = []

    if let title = data.metadata?.title {
      let cleanTitle = title.replacingOccurrences(of: "| Apple Developer Documentation", with: "")
        .trimmingCharacters(in: .whitespaces)
      lines.append("title: \(cleanTitle)")
    } else if let swiftTitle = data.interfaceLanguages?.swift?.first?.title {
      lines.append("title: \(swiftTitle)")
    }

    if let abstract = data.abstract {
      let description =
        abstract
        .filter { $0.type == "text" }
        .compactMap { $0.text }
        .joined()
        .trimmingCharacters(in: .whitespaces)
      if !description.isEmpty {
        lines.append("description: \(description)")
      }
    }

    lines.append("source: \(sourceURL)")

    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    lines.append("timestamp: \(formatter.string(from: Date()))")

    return "---\n\(lines.joined(separator: "\n"))\n---\n\n"
  }

  static func generateBreadcrumbs(_ sourceURL: String) -> String {
    guard let url = URL(string: sourceURL) else { return "" }
    let pathParts = url.pathComponents.filter { $0 != "/" }

    if pathParts.count < 3 { return "" }

    let framework = pathParts[1]
    let capitalizedFramework = framework.prefix(1).uppercased() + framework.dropFirst()
    var breadcrumbs = "**Navigation:** [\(capitalizedFramework)](/documentation/\(framework))"

    if pathParts.count > 3 {
      for i in 2..<(pathParts.count - 1) {
        let part = pathParts[i]
        let path = pathParts[0...i].joined(separator: "/")
        breadcrumbs += " › [\(part)](/\(path))"
      }
    }

    return "\(breadcrumbs)\n\n"
  }

  static func renderDeclarations(_ declarations: [Declaration]) -> String {
    var markdown = ""
    for decl in declarations {
      guard let tokens = decl.tokens else { continue }
      let code =
        tokens
        .compactMap { $0.text }
        .joined()
        .trimmingCharacters(in: .whitespacesAndNewlines)
      if !code.isEmpty {
        markdown += "```swift\n\(code)\n```\n\n"
      }
    }
    return markdown
  }

  static func renderParameters(_ params: [Parameter], references: [String: ContentItem]?) -> String
  {
    if params.isEmpty { return "" }
    var markdown = "## Parameters\n\n"
    for param in params {
      markdown += "**\(param.name)**\n\n"
      if let content = param.content {
        let paramText = ContentRenderer.renderContentArray(
          content, references: references, depth: 0)
        markdown += "\(paramText)\n\n"
      }
    }
    return markdown
  }

  // MARK: - Delegating to ContentRenderer

  static func renderContentArray(
    _ content: [ContentItem], references: [String: ContentItem]?, depth: Int = 0
  ) -> String {
    ContentRenderer.renderContentArray(content, references: references, depth: depth)
  }

  static func renderInlineContent(
    _ inlineContent: [ContentItem], references: [String: ContentItem]?, depth: Int = 0
  ) -> String {
    ContentRenderer.renderInlineContent(inlineContent, references: references, depth: depth)
  }

  static func convertIdentifierToURL(_ identifier: String, references: [String: ContentItem]?)
    -> String
  {
    ContentRenderer.convertIdentifierToURL(identifier, references: references)
  }

  static func extractTitleFromIdentifier(_ identifier: String) -> String {
    ContentRenderer.extractTitleFromIdentifier(identifier)
  }

  static func mapAsideStyleToCallout(_ style: String) -> String {
    ContentRenderer.mapAsideStyleToCallout(style)
  }

  // MARK: - Relationship / Topic / SeeAlso / Index (reference-specific)

  static func renderRelationships(
    _ rels: [ContentItem], variants: [Variant]?, refs: [String: ContentItem]?
  ) -> String {
    ContentRenderer.renderRelationships(rels, variants: variants, refs: refs)
  }

  static func renderTopicSections(
    _ topics: [TopicSection], variants: [Variant]?, refs: [String: ContentItem]?
  ) -> String {
    var markdown = ""
    for topic in topics {
      guard !topic.title.isEmpty else { continue }
      markdown += "## \(topic.title)\n\n"
      if let identifiers = topic.identifiers {
        for id in identifiers {
          let info = variants?.first { $0.identifier == id }
          let reference = refs?[id]
          if info != nil || reference != nil {
            let displayTitle =
              info?.title ?? reference?.title ?? ContentRenderer.extractTitleFromIdentifier(id)
            let url = ContentRenderer.convertIdentifierToURL(id, references: refs)
            var abstractText = ""
            if let infoAbstract = info?.abstract {
              abstractText = infoAbstract.compactMap { $0.text }.joined()
            } else if let refAbstract = reference?.abstract {
              abstractText = refAbstract.compactMap { $0.text }.joined()
            }
            markdown += "- [\(displayTitle)](\(url))"
            if !abstractText.isEmpty {
              markdown += " \(abstractText)"
            }
            markdown += "\n"
          } else {
            let displayTitle = ContentRenderer.extractTitleFromIdentifier(id)
            let url = ContentRenderer.convertIdentifierToURL(id, references: refs)
            markdown += "- [\(displayTitle)](\(url))\n"
          }
        }
        markdown += "\n"
      }
    }
    return markdown
  }

  static func renderIndexContent(_ children: [IndexContentItem]) -> String {
    renderIndexContentWithIndent(children, headingLevel: 2)
  }

  static func renderIndexContentWithIndent(_ children: [IndexContentItem], headingLevel: Int)
    -> String
  {
    var markdown = ""
    for (i, child) in children.enumerated() {
      if child.type == "groupMarker" {
        if i > 0 { markdown += "\n" }
        let hashes = String(repeating: "#", count: min(headingLevel, 6))
        markdown += "\(hashes) \(child.title ?? "")\n\n"
      } else if let path = child.path, let title = child.title {
        let beta = child.beta == true ? " **Beta**" : ""
        markdown += "- [\(title)](\(path))\(beta)\n"
        if let nestedChildren = child.children {
          markdown += "\n"
          markdown += renderIndexContentWithIndent(nestedChildren, headingLevel: headingLevel + 1)
        }
      }
    }
    return markdown
  }

  static func renderSeeAlso(
    _ sections: [SeeAlsoSection], variants: [Variant]?, refs: [String: ContentItem]?
  ) -> String {
    var markdown = ""
    for section in sections {
      guard let identifiers = section.identifiers, !section.title.isEmpty else { continue }
      markdown += "## \(section.title)\n\n"
      for id in identifiers {
        let info = variants?.first { $0.identifier == id }
        let reference = refs?[id]
        let displayTitle =
          info?.title ?? reference?.title ?? ContentRenderer.extractTitleFromIdentifier(id)
        let url = ContentRenderer.convertIdentifierToURL(id, references: refs)
        markdown += "- [\(displayTitle)](\(url))\n"
      }
      markdown += "\n"
    }
    return markdown
  }
}
