import Foundation
import Testing
@testable import AppleDocsCore

@Suite("Smoke Tests")
struct SmokeTests {
    static let fixtureData: AppleDocJSON = {
        let url = Bundle.module.url(forResource: "array", withExtension: "json", subdirectory: "Fixtures")!
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode(AppleDocJSON.self, from: data)
    }()

    @Test("Successfully imports Apple Array documentation JSON")
    func importJSON() {
        let data = SmokeTests.fixtureData
        #expect(data.topicSections != nil)
        #expect(data.topicSections!.count > 0)
    }

    @Test("Renders complete Swift Array documentation")
    func renderArrayDoc() {
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )

        #expect(result.count > 1000)
        #expect(result.hasPrefix("---\n"))
        #expect(result.contains("source: https://developer.apple.com/documentation/swift/array"))
        #expect(result.contains("**Navigation:** [Swift](/documentation/swift)"))
        #expect(result.contains("## Creating an Array"))
        #expect(result.contains("## Inspecting an Array"))
        #expect(result.contains("## Accessing Elements"))
        #expect(result.contains("*Generated by [swift-developer-docs-mcp]"))
        #expect(result.contains("*This is unofficial content. All documentation belongs to Apple Inc.*"))
        #expect(!result.contains("[Content too deeply nested]"))
        #expect(!result.contains("[Inline content too deeply nested]"))
        #expect(!result.contains("[object Object]"))
    }

    @Test("Processes large dataset within performance limits")
    func performance() {
        let start = Date()
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )
        let elapsed = Date().timeIntervalSince(start)

        #expect(elapsed < 8.0)
        #expect(result.count > 5000)

        let topicSectionCount = result.components(separatedBy: "\n## ").count - 1
        #expect(topicSectionCount > 10)

        let linkPattern = try! Regex(#"\[.*?\]\(/documentation/swift/array/"#)
        let linkCount = result.matches(of: linkPattern).count
        #expect(linkCount > 20)
    }

    @Test("Validates Apple documentation data structure")
    func dataStructure() {
        let data = SmokeTests.fixtureData
        #expect(data.topicSections != nil)

        let topicTitles = data.topicSections!.map { $0.title }
        #expect(topicTitles.contains("Creating an Array"))
        #expect(topicTitles.contains("Inspecting an Array"))
        #expect(topicTitles.contains("Accessing Elements"))

        for section in data.topicSections! {
            #expect(section.identifiers != nil)
            if let identifiers = section.identifiers, !identifiers.isEmpty {
                for id in identifiers {
                    #expect(id.hasPrefix("doc://com.apple."))
                }
            }
        }
    }

    @Test("Renders all identifiers from source data")
    func identifierCoverage() {
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )

        var totalIdentifiers = 0
        for section in SmokeTests.fixtureData.topicSections ?? [] {
            totalIdentifiers += section.identifiers?.count ?? 0
        }

        #expect(totalIdentifiers > 50)

        let linkPattern = try! Regex(#"\[.*?\]\(/documentation/swift/array/.*?\)"#)
        let linkCount = result.matches(of: linkPattern).count
        #expect(linkCount > totalIdentifiers / 2)
    }

    @Test("Converts method names to readable format")
    func methodNames() {
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )
        #expect(result.contains("[randomElement()]"))
        #expect(result.contains("[isEmpty]"))
        #expect(result.contains("[firstIndex"))
    }

    @Test("Preserves method signatures with parentheses")
    func methodSignatures() {
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )
        #expect(result.contains("[init()]"))
        #expect(result.contains("[append(_:)]"))
        #expect(result.contains("[insert(_:at:)]"))
        #expect(result.contains("[remove(at:)]"))
        #expect(!result.contains("[init ()]"))
        #expect(!result.contains("[append (_:)]"))
    }

    @Test("Generates valid markdown structure")
    func markdownStructure() {
        let result = DocumentRenderer.renderFromJSON(
            SmokeTests.fixtureData,
            sourceURL: "https://developer.apple.com/documentation/swift/array"
        )

        let headingPattern = try! Regex(#"^#{1,6}\s+.+$"#.self)
        let headings = result.split(separator: "\n").filter { line in
            line.wholeMatch(of: headingPattern) != nil
        }
        #expect(headings.count > 10)

        let listItemPattern = try! Regex(#"^- \[.+?\]\(.+?\)"#)
        let listItems = result.split(separator: "\n").filter { line in
            line.wholeMatch(of: listItemPattern) != nil || line.hasPrefix("- [")
        }
        #expect(listItems.count > 20)
    }
}
